export const apiUrl = process.env.NODE_ENV !== 'production' ? 'http://localhost:5000/api' : 'https://fierce-wave-20551.herokuapp.com/api'

export const LOCAL_STORAGE_TOKEN_NAME = 'learnit-mern'
export const USERS_LOADED_SUCCESS = 'USERS_LOADED_SUCCESS'
export const USERS_LOADED_FAIL = 'USERS_LOADED_FAIL'
export const ADD_USER = 'ADD_USER'
export const FIND_USER = 'FIND_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const DELETE_USER = 'DELETE_USER'

export const POSTS_LOADED_SUCCESS = 'POSTS_LOADED_SUCCESS'
export const POSTS_LOADED_FAIL = 'POSTS_LOADED_FAIL'
export const ADD_POST = 'ADD_POST'
export const DELETE_POST = 'DELETE_POST'
export const FIND_POST = 'FIND_POST'
export const UPDATE_POST = 'UPDATE_POST'

export const CRUISES_LOADED_SUCCESS = 'CRUISES_LOADED_SUCCESS'
export const CRUISES_LOADED_FAIL = 'CRUISES_LOADED_FAIL'
export const ADD_CRUISE = 'ADD_CRUISE'
export const FIND_CRUISE = 'FIND_CRUISE'
export const UPDATE_CRUISE = 'UPDATE_CRUISE'
export const DELETE_CRUISE = 'DELETE_CRUISE'
export const FIND_A_CRUISE = 'FIND_A_CRUISE'

export const ROOMS_LOADED_SUCCESS = 'ROOMS_LOADED_SUCCESS'
export const ROOMS_LOADED_FAIL = 'ROOMS_LOADED_FAIL'

// category
export const CATEGORIES_LOADED_SUCCESS = 'CATEGORIES_LOADED_SUCCESS'
export const CATEGORIES_LOADED_FAIL = 'CATEGORIES_LOADED_FAIL'
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const FIND_CATEGORY = 'FIND_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'

// materials
export const MATERIALS_LOADED_SUCCESS = 'MATERIALS_LOADED_SUCCESS'
export const MATERIALS_LOADED_FAIL = 'MATERIALS_LOADED_FAIL'
export const ADD_MATERIAL = 'ADD_MATERIAL'
export const DELETE_MATERIAL = 'DELETE_MATERIAL'
export const FIND_MATERIAL = 'FIND_MATERIAL'
export const UPDATE_MATERIAL = 'UPDATE_MATERIAL'

// CONSTRUCTIONs
export const CONSTRUCTIONS_LOADED_SUCCESS = 'CONSTRUCTIONS_LOADED_SUCCESS'
export const CONSTRUCTIONS_LOADED_FAIL = 'CONSTRUCTIONS_LOADED_FAIL'
export const ADD_CONSTRUCTION = 'ADD_CONSTRUCTION'
export const DELETE_CONSTRUCTION = 'DELETE_CONSTRUCTION'
export const FIND_CONSTRUCTION = 'FIND_CONSTRUCTION'
export const UPDATE_CONSTRUCTION = 'UPDATE_CONSTRUCTION'

// WAREHOUSES
export const WAREHOUSES_LOADED_SUCCESS = 'WAREHOUSES_LOADED_SUCCESS'
export const WAREHOUSES_LOADED_FAIL = 'WAREHOUSES_LOADED_FAIL'
export const ADD_WAREHOUSE = 'ADD_WAREHOUSE'
export const DELETE_WAREHOUSE = 'DELETE_WAREHOUSE'
export const FIND_WAREHOUSE = 'FIND_WAREHOUSE'
export const UPDATE_WAREHOUSE = 'UPDATE_WAREHOUSE'

// UNIT
export const UNITS_LOADED_SUCCESS = 'UNITS_LOADED_SUCCESS'
export const UNITS_LOADED_FAIL = 'UNITS_LOADED_FAIL'
export const ADD_UNIT = 'ADD_UNIT'
export const DELETE_UNIT = 'DELETE_UNIT'
export const FIND_UNIT = 'FIND_UNIT'
export const UPDATE_UNIT = 'UPDATE_UNIT'

//DEPOT
export const DEPOTS_LOADED_SUCCESS = 'DEPOTS_LOADED_SUCCESS'
export const DEPOTS_LOADED_FAIL = 'DEPOTS_LOADED_FAIL'
export const ADD_DEPOT = 'ADD_DEPOT'
export const DELETE_DEPOT = 'DELETE_DEPOT'
export const FIND_DEPOT = 'FIND_DEPOT'
export const UPDATE_DEPOT = 'UPDATE_DEPOT'

//EXPORTS
export const EXPORTS_LOADED_SUCCESS = 'EXPORTS_LOADED_SUCCESS'
export const EXPORTS_LOADED_FAIL = 'EXPORTS_LOADED_FAIL'
export const ADD_EXPORT = 'ADD_EXPORT'
export const DELETE_EXPORT = 'DELETE_EXPORT'
export const FIND_EXPORT = 'FIND_EXPORT'
export const UPDATE_EXPORT = 'UPDATE_EXPORT'

//staff
export const STAFF_LOADED_SUCCESS = 'STAFF_LOADED_SUCCESS'
export const STAFF_LOADED_FAIL = 'STAFF_LOADED_FAIL'
export const ADD_STAFF = 'ADD_STAFF'
export const DELETE_STAFF = 'DELETE_STAFF'
export const FIND_STAFF = 'FIND_STAFF'
export const UPDATE_STAFF = 'UPDATE_STAFF'